In [1]:
import numpy as np
import pandas as pd

In [39]:
df = pd.read_excel('adel.xlsx', sheet_name=1, index_col=0)

In [40]:
df.head()

,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,...,v16,v17,v18,v19,v20,v21,v22,v23,v24,v25
ID,,,,,,,,,,,,,,,,,,,,,
1,43,4205,20,210.25,97.79,3442.75,40.08,1.19,21,43,...,269.87,60.66,19.83,172.13,4.003023,1.00,98.0,100.0,8,6.722689
2,143,5344,26,205.54,37.37,2420.70,76.96,2.30,35,72,...,221.73,58.26,23.83,93.10,0.651049,0.96,86.4,97.9,9,3.910000
3,77,4760,24,198.33,61.82,2727.50,39.62,2.36,36,68,...,256.38,55.42,23.92,113.64,1.475844,1.17,91.7,100.0,16,6.780000
4,723,24186,49,493.59,33.45,7241.18,273.80,3.77,77,129,...,349.13,87.00,45.40,147.77,0.204385,0.73,55.8,69.6,24,6.370000
5,238,9549,39,244.85,40.12,3592.97,86.61,4.10,55,94,...,225.29,66.68,28.20,92.12,0.387059,0.74,78.2,94.1,18,4.390000

In [63]:
def get_correlation_indices(df, threshold):
    """
    Returns the indices where the Pearson correlation coefficients are
    above the given threshold in the given dataframe.
    """
    pearsonr = np.corrcoef(df, rowvar=False)
    indices = np.where(pearsonr.reshape(len(df.columns) ** 2) > threshold)[0]
    
    # The two conditions here make sure we do not include diagonal elements
    # (trivial), and that we include each pair only once.
    indices_2d = [[x // 26, x % 26] for x in indices if x // 26 != x % 26 and x // 26 < x % 26]
    
    # Display the correlations in a matrix to make it look easier
    index = 0

    for i in range(26):
        count = 0
        for j in range(26):
            if index < len(indices_2d) and i == indices_2d[index][0] \
                and j == indices_2d[index][1] and i < j:
                print('*', end=' ')
                index += 1
                count += 1
            elif i > j:
                print(' ', end=' ')
            else:
                print('-', end=' ')
        print(' ', count)
    
    return indices_2d

In [64]:
np.array(df)[indices_2d[0][0]][indices_2d[0][1]]

2.3

In [65]:
indices = get_correlation_indices(df, 0.8)

- - - - - - * - - - - - - - - - - - - - - - - - - -   1
  - * - * - - * * - - - * - * - * * - - - - * - - -   9
    - - - - - - - - - - - - - - - - - - - - - - * -   1
      - - * * * - * * * * * - * - - - - * * - - - -   11
        - - - - - - - - * - - - - - - - - - * - * -   3
          - - * * - * * * * - - - - - * * - - - - -   8
            - - - - - - - - - - - - - - - - - - - -   0
              - - - - - - - - - - - - * - * - * - -   3
                - * - - - - - - - - * - * - * - - *   5
                  - - - - - - - - - - * - - - - * *   3
                    - - - - - - - - - - - - - * * -   2
                      - - - - - - * - * - - * * * *   6
                        - - * - * - * - - * * * - -   6
                          - - * - - - - * * * - * *   6
                            - - * - - * * * * * * *   8
                              - - - * * * - * * * *   7
                                - * * * * * - * * *   8
                                  - - - * - - * * -   3
                                    - - - - - - - -   0
                                      - - - - - - -   0
                                        - - - - - -   0
                                          - - - - *   1
                                            - - - -   0
                                              - - *   1
                                                - -   0
                                                  -   0